version: '3'
services:
  flask:
    # build Dockerfile
    build: .
    network_mode: "host"
    ports:
      #- "${MY_DOCKER_IP:-127.0.0.1}:5000:5000"
      - "5000:5000"
    depends_on:
      - "db"

  db:
    container_name: postgresql
    restart: always
    image: public.ecr.aws/y5z1i2v3/zhongpengqun:postgres9.6
    privileged: true       # to solve some privilege issues
    ports:
      - "6432:5432"
      
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata

    volumes:
      - .pgdata:/var/lib/postgresql/data/pgdata