"""empty message

Revision ID: 2ed6a7751c30
Revises: 
Create Date: 2021-03-20 22:28:20.060737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ed6a7751c30'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phrases',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spell', sa.String(length=200), nullable=True, comment=u'spell'),
    sa.Column('meaning', sa.String(length=500), nullable=True, comment=u'meaning'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spell')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phrases')
    # ### end Alembic commands ###
