"""empty message

Revision ID: 37266abab1d3
Revises: b63b8197ec74
Create Date: 2021-05-08 11:03:08.764716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37266abab1d3'
down_revision = 'b63b8197ec74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('video_embed_link', sa.String(length=800), nullable=True, comment=u'embed src link if this article has relevant video.'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'video_embed_link')
    # ### end Alembic commands ###
