"""empty message

Revision ID: 3df77faaabc7
Revises: 928e60160f08
Create Date: 2021-05-04 20:43:16.534580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3df77faaabc7'
down_revision = '928e60160f08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'current_topic',
               existing_type=sa.INTEGER(),
               comment=u'currently learning topic',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'current_topic',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment=u'currently learning topic',
               existing_nullable=True)
    # ### end Alembic commands ###
