"""empty message

Revision ID: 928e60160f08
Revises: af0d8f042994
Create Date: 2021-05-04 14:30:54.039260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '928e60160f08'
down_revision = 'af0d8f042994'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_topic', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'current_topic')
    # ### end Alembic commands ###
