"""empty message

Revision ID: b63b8197ec74
Revises: 3df77faaabc7
Create Date: 2021-05-04 20:47:25.077779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b63b8197ec74'
down_revision = '3df77faaabc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_topic', sa.String(length=200), nullable=True, comment=u'currently learning topic'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'current_topic')
    # ### end Alembic commands ###
