"""empty message

Revision ID: d5dbeac0cbae
Revises: 2ed6a7751c30
Create Date: 2021-03-20 22:39:11.933968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5dbeac0cbae'
down_revision = '2ed6a7751c30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('soramimi', sa.String(length=500), nullable=True, comment=u'soramimi'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('words', 'soramimi')
    # ### end Alembic commands ###
